name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_PAYMENT_API_URL: ${{ secrets.VITE_PAYMENT_API_URL }}
      VITE_HCAPTCHA_SITE_KEY: ${{ secrets.VITE_HCAPTCHA_SITE_KEY }}
      VITE_CONTENTFUL_SPACE: ${{ secrets.VITE_CONTENTFUL_SPACE }}
      VITE_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.VITE_CONTENTFUL_ACCESS_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the Vite app
        run: npm run deploy

      - name: Configure Git identity
        run: |
          git config --global user.email "m4teks93@gmail.com"
          git config --global user.name "MateuszSlezak"

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: www/
          exclude: .env